version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p RCM/bin RCM/lib RCM/conf
      - touch RCM/bin/startup.sh RCM/conf/application.properties
      - cp target/messageUtil-1.0.jar RCM/lib
      - pwd
      - echo "java $Java_details ../lib/rcmmessageUtil-1.0.jar">> RCM/bin/startup.sh

artifacts:
  files:
    - 'RCM/**/*'
